openapi: 3.0.3
info:
  title: Songify - OpenAPI 3.0
  description: |-
    This is an API gives you information about artists, releases and recordings. 
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Songify
  url: https://github.com/rmerchanc/songify
servers:
- url: https://petstore3.swagger.io/api/v3 # no sé cuál será
tags:
- name: artist
  description: Everything about artists
  externalDocs:
    description: Find out more about artists
    url: https://musicbrainz.org/doc/Artist
- name: release
  description: Everything about releases
  externalDocs:
    description: Find out more about releases
    url: https://musicbrainz.org/doc/Release
- name: recording
  description: Everything about recordings
  externalDocs:
    description: Find out more about recordings
    url: https://musicbrainz.org/doc/Recording
paths:
  /artists:
    get: 
      summary: GET all the artists of the API
      description: Retreives all the information of the available artists
      responses: 
        '200': 
          description: All the information of the artists was successfully retreived
          content:
            'application/json':
              schema: 
                $ref: "#/components/schemas/artists"
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request
components:
  schemas: 
    artists: 
      type: array
      items: 
        $ref: "#/components/schemas/artist"
      example: [{
        "id": 1,
        "name": "Coldplay",
        "type": "Group",
        "area": "United Kingdom",
        "begin_date": "1996-09",
        "url_releases": "https://petstore3.swagger.io/api/v3/artist/1/releases",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/recordings"
      }] 
    artist: 
      type: object
      properties: 
        id: 
          type: integer
          minimum: 1
          description: Unique identifier for an artist
        name: 
          type: string
          description: Official name of the artist, it could be a person or a band
        type: 
          type: string
          enum: ["Person", "Group", "Orchestra", "Choir"]
          description: Type which indicates whether an artist is a person, a group, or something else.
        gender: 
          type: string
          enum: ["Male", "Female", "Neither"]
          description: Gender states wehther a person or character identifies as a male, female or neither. Groups do not have genders. 
        area: 
          type: string
          description: Area with which an artist is identified with. Mostly, it is birth/formation country. 
        begin_date: 
          type: string
          format: date
          description: Begin date represents the date of birth or the group formation
        end_date: 
          type: string
          format: date
          description: End date represents the date of death or the group last dissolution
        url_releases: 
          type: string
          format: uri
          description: URI to the releases of this artist
        url_recordings: 
          type: string
          format: uri
          description: URI to the recordings of this artist
      required: 
        - id
        - name
        - type
        - area
        - begin_date
        - url_releases
        - url_recordings
      additionalProperties: false
      example: {
        "id": 1,
        "name": "Coldplay",
        "type": "Group",
        "area": "United Kingdom",
        "begin_date": "1996-09",
        "url_releases": "https://petstore3.swagger.io/api/v3/artist/1/releases",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/recordings"
      }