openapi: 3.0.3
info:
  title: Songify - OpenAPI 3.0
  description: |-
    This is an API gives you information about artists, releases and recordings. 
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Songify
  url: https://github.com/rmerchanc/songify
servers:
- url: https://petstore3.swagger.io/api/v3 # no sé cuál será
tags:
- name: artist
  description: Everything about artists
  externalDocs:
    description: Find out more about artists
    url: https://musicbrainz.org/doc/Artist
- name: release
  description: Everything about releases
  externalDocs:
    description: Find out more about releases
    url: https://musicbrainz.org/doc/Release
- name: recording
  description: Everything about recordings
  externalDocs:
    description: Find out more about recordings
    url: https://musicbrainz.org/doc/Recording
paths:
  /artist:
    get: 
      summary: GET all the artists of the API
      description: Retreives all the information of the available artists
      responses: 
        '200': 
          description: All the information of the artists was successfully retreived
          content:
            'application/json':
              schema: 
                $ref: "#/components/schemas/artists"
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request
    post:
      summary: POST a new artist 
      description: Registers a new artist based on the information provided by the user
      requestBody:
        required: true
        content: 
          'application/json':
            schema: 
              $ref: "#/components/schemas/artist"
      responses: 
        '201': 
          description: Created a new artist successfully based on the information provided
          content:
            'application/json':
              schema: 
                $ref: "#/components/schemas/new_element"
        '400':
          description: Bad request performed by the client due to invalid parameters
          content: 
            'application/json':
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Unauthorized request due to missing credentials 
          content: 
            'application/json':
              schema:
                $ref: '#/components/schemas/error' 
        '403':
          description: Fordibben access due to permanent restrictions
          content: 
            'application/json':
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request
  /artist/release:
    get:
      summary: GET all the releases from a specific artist of the API
      description: Retreives all the information of the available releases from an artist
      responses: 
        '200': 
          description: All the information of the releases from this artist was successfully retreived
          content:
            'application/json':
              schema: 
                $ref: "#/components/schemas/artists_release" 
        '500':
          description: The server encountered an unexpected condition that prevented it from fulfilling the request
components:
  schemas: 
    id: 
      type: integer
      minimum: 1
      description: Unique identifier for an artist
    artists: 
      type: array
      items: 
        $ref: "#/components/schemas/artist"
      example: [
        {
        "id": 1,
        "name": "Coldplay",
        "type": "Group",
        "area": "United Kingdom",
        "begin_date": "1996-09",
        "url_releases": "https://petstore3.swagger.io/api/v3/artist/1/releases",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/recordings"
        }, 
        {
        "id": 2,
        "name": "John Williams",
        "type": "Person",
        "gender": "Male",
        "area": "Australia",
        "begin_date": "1941-04-24",
        "url_releases": "https://petstore3.swagger.io/api/v3/artist/2/releases",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/2/recordings"
        }
      ] 
    artist: 
      type: object
      properties: 
        id: 
          $ref: "#/components/schemas/id"  
        name: 
          type: string
          description: Official name of the artist, it could be a person or a band
        type: 
          type: string
          enum: ["Person", "Group", "Orchestra", "Choir"]
          description: Type which indicates whether an artist is a person, a group, or something else.
        gender: 
          type: string
          enum: ["Male", "Female", "Neither"]
          description: Gender states wehther a person or character identifies as a male, female or neither. Groups do not have genders. 
        area: 
          type: string
          description: Area with which an artist is identified with. Mostly, it is birth/formation country. 
        begin_date: 
          type: string
          format: date
          description: Begin date represents the date of birth or the group formation
        end_date: 
          type: string
          format: date
          description: End date represents the date of death or the group last dissolution
        url_releases: 
          type: string
          format: uri
          description: URI to the releases of this artist
        url_recordings: 
          type: string
          format: uri
          description: URI to the recordings of this artist
      required: 
        - id
        - name
        - type
        - area
        - begin_date
        - url_releases
        - url_recordings
      additionalProperties: false
      example: {
        "id": 1,
        "name": "Coldplay",
        "type": "Group",
        "area": "United Kingdom",
        "begin_date": "1996-09",
        "url_releases": "https://petstore3.swagger.io/api/v3/artist/1/releases",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/recordings"
      }
    artists_release:
      type: array
      items: 
        $ref: "#/components/schemas/artist_release"
      example: [
        {
        "id": 1,
        "title": "Parachutes",
        "artist": "Coldplay",
        "date": "2000-07-10",
        "country": "United Kingdom",
        "label": "Parlophone",
        "language": "en",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/release/1/recordings"
        }, 
        {
        "id": 2,
        "title": "A rush of blood to the head",
        "artist": "Coldplay",
        "date": "2002-08-26",
        "country": "United Kingdom",
        "label": "Parlophone",
        "language": "en",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/release/2/recordings"
        }
      ] 
    artist_release:
      type: object
      properties: 
        id: 
          type: integer
          minimum: 1
          description: Unique identifier for an artist's release
        title: 
          type: string
          description: Official name of the release
        artist: 
          type: string
          description: Official name of the artist, it could be a person or a band
        date: 
          type: string
          format: date
          description: Official date of the artist's release 
        country: 
          type: string
          description: Country of the artist's release. Mostly, it is birth/formation country. 
        language: 
          type: string
          description: Official language of the artist's release
        url_recordings: 
          type: string
          format: uri
          description: URI to the recordings of this release
      required:
        - id
        - title
        - artist
        - date
        - country
        - language
        - url_recordings
      additionalProperties: false
      example: [
        {
        "id": 1,
        "title": "Parachutes",
        "artist": "Coldplay",
        "date": "2000-07-10",
        "country": "United Kingdom",
        "label": "Parlophone",
        "language": "en",
        "url_recordings": "https://petstore3.swagger.io/api/v3/artist/1/release/1/recordings"
        }
      ]
    new_element:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        url: 
          description: Link to the new element created
          type: string
          format: uri
      example: {
        "id": 1,
        "url": "https://petstore3.swagger.io/api/v3/artist/1"
      }
    error:
      type: object
      properties:
        error:
          type: string
          enum: ["Bad request", "Unauthorized", "Fordibben"]
        mensaje: 
          type: string
          enum: ["Bad request performed by the client due to invalid parameters", 
                 "Unauthorized request due to missing credentials", 
                 "Fordibben access due to permanent restrictions"]
      required:
      - error
      - mensaje
      additionalProperties: false
      example: {
        "error": "Bad request",
        "mensaje": "Bad request performed by the client due to invalid parameters"
      }
    